

services:
  db:
    image: mongo:latest
    container_name: searchengine_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - app_network

  mongo-express:
    image: mongo-express:latest
    container_name: searchengine_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - db
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: searchengine_backend
    restart: always
    environment:
      - SERVER_PORT=8080
      - SPRING_DATA_MONGODB_URI=${SPRING_DATA_MONGODB_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
    ports:
      - "8080:8080"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: searchengine_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
