spring.application.name=code-search-platform

# Server Configuration
server.port=8082

spring.data.mongodb.uri=mongodb://db:27017/code_search_db
logging.file.name=spring.log
logging.level.org.springframework.web=DEBUG

nvidia.api.key=${NVIDIA_API_KEY}
nvidia.api.url=https://integrate.api.nvidia.com/v1/chat/completions
